os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.10.0"

branches:
  only:
  - master

deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY
  secret_access_key: $S3_SECRET_ACCESS_KEY
  bucket: "330manager"
  skip_cleanup: true
  upload-dir: back